NumPy

In [3]:
import numpy as np

1.Create a 1D array from a list.


In [2]:
lst=(11,22,33,44)
arr1=np.array(lst)
arr1

array([11, 22, 33, 44])

2. Create a 3x3 array of zeros.


In [3]:
arr2=np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3. Create a 2x2 array of ones.

In [4]:
arr3=np.ones((2,2))
arr3

array([[1., 1.],
       [1., 1.]])

4. Generate array from 0 to 10 (exclusive).

In [6]:
arr4=np.arange(0,10,1)
arr4


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5. Create 5 evenly spaced numbers between 0 and 1.


In [7]:
arr5=np.linspace(0,1,5)
arr5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

6. Create a 4x4 identity matrix.

In [9]:
arr6=np.eye(4,)
arr6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

7. Reshape 1D array to 2D.

In [13]:
arr7=np.array([11,22,33,44])
arr8=arr7.reshape(2,2)
arr8

array([[11, 22],
       [33, 44]])

8. Get the shape and dtype of an array.

In [18]:
arr9=np.array([[1,2,3,4,5,6]])
print(np.shape(arr9))
arr9.dtype

(1, 6)


dtype('int32')

9. Reverse a NumPy array.

In [4]:
arr10=np.array([[5,4,3,2,1]])
arr10[::-1]

array([[5, 4, 3, 2, 1]])

10. Extract even numbers from an array.

In [26]:
arr11=np.array([4,5,6,7,8])
for num in arr11:
    if num %2 ==0:
        print(num)

4
6
8


11. Find the max in each row.

In [30]:
arr12=np.array([[1,2,3,4],[5,6,7,8]])
arr12.max(1)

array([4, 8])

12. Compute the mean, std, and median of an array.


In [38]:
print("Mean =",arr12.mean(axis=1))
print("Standard Deviation = ",arr12.std(axis=1))
print("Median = ",np.median(arr12,axis=1))

Mean = [2.5 6.5]
Standard Deviation =  [1.11803399 1.11803399]
Median =  [2.5 6.5]


13. Stack two arrays vertically.

In [40]:
arr13=([[9,8,7],[6,5,4]])
arr14=([[1,2,3],[7,6,9]])
np.concatenate((arr13,arr14),axis=0)

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3],
       [7, 6, 9]])

14. Stack two arrays horizontally.

In [41]:
np.concatenate((arr13,arr14),axis=1)

array([[9, 8, 7, 1, 2, 3],
       [6, 5, 4, 7, 6, 9]])

15. Stack two arrays horizontally.


In [42]:
np.concatenate((arr13,arr14),axis=1)

array([[9, 8, 7, 1, 2, 3],
       [6, 5, 4, 7, 6, 9]])

16. Find the unique values and their counts.


In [47]:
arr15=np.array([[1,2,3,4,5,6],[8,7,3,6,4,5]])
unique,counts=np.unique(arr15, return_counts=True)
print(np.asarray((unique, counts)).T)

[[1 1]
 [2 1]
 [3 2]
 [4 2]
 [5 2]
 [6 2]
 [7 1]
 [8 1]]


17. Replace NaN with column means.


In [4]:
#17. Replace NaN with column means.
arr16 = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
col_mean = np.nanmean(arr16, axis=0)
print("Column means:", col_mean)


Column means: [4.  5.  7.5]


18. Get index of min and max values.


19. Create a 3D array of random integers.



In [ ]:
arr18 = np.random.randint(0, 10, size=(2, 3, 4))
print("3D array of random integers:\n", arr18)

3D array of random integers:
 [[[6 5 3 5]
  [4 8 9 7]
  [6 3 4 0]]

 [[7 2 3 4]
  [1 5 7 4]
  [4 7 9 4]]]


20. Use np.where() to replace values


In [5]:
arr19 = np.array([[1, 2, 3], [4, 5, 6]])
arr19_replaced = np.where(arr19 > 3, -1, arr19)
print('Array after np.where():\n', arr19_replaced)

Array after np.where():
 [[ 1  2  3]
 [-1 -1 -1]]


Pandas

In [6]:
import pandas as pd

1. Create a Series using a Python list.


In [55]:
series1 = pd.Series([10, 20, 30, 40,50])
print("Series from list:\n",series1)


Series from list:
 0    10
1    20
2    30
3    40
4    50
dtype: int64


2. Create a Series with custom string indices.




In [ ]:
series2 = pd.Series([100, 200, 300], index=['a', 'b', 'c'])
print("Series with custom indices:\n", series2)

Series with custom indices:
 a    100
b    200
c    300
dtype: int64


3. Create a Series from a dictionary.


In [53]:
series3 = pd.Series({'x': 1, 'y': 2, 'z': 3})
print("Series from dictionary:\n", series3)

Series from dictionary:
 x    1
y    2
z    3
dtype: int64


4. Access first 3 elements of a Series.


In [ ]:
print("First 3 elements of series1:\n", series1.head(3))

First 3 elements of series1:
 0    10
1    20
2    30
dtype: int64


5. Filter Series elements greater than 50.



In [59]:
series4 = pd.Series([10, 20, 30, 40,50,60,70,80,90,100])
filtered_series = series4[series4 > 50]
print("Filtered Series (elements > 50):\n", filtered_series)

Filtered Series (elements > 50):
 5     60
6     70
7     80
8     90
9    100
dtype: int64


6. Add two Series with different indices.



In [4]:
series5 = pd.Series([1, 2, 3, 4, 5])
series6=pd.Series([6,7,8,9,10])
print("Addition of two series : \n",series5+series6)

Addition of two series : 
 0     7
1     9
2    11
3    13
4    15
dtype: int64



7. Multiply a Series by a scalar.


In [6]:
series7=pd.Series([1,2,3,4,5])
print(series7*2)

0     2
1     4
2     6
3     8
4    10
dtype: int64


8. Use .multiply() method to multiply with scalar.


In [ ]:
series8 = pd.Series([1, 2, 3, 4, 5])
series8_multiplied = series8.multiply(3)    
series8_multiplied.name = 'Multiplied Series'
print("Series after multiplication with 3:\n", series8_multiplied)

Series after multiplication with 3:
 0     3
1     6
2     9
3    12
4    15
Name: Multiplied Series, dtype: int64


10. Sort Series by values descending.


In [ ]:
series9 = pd.Series([5, 2, 8, 1, 4])
sorted_series = series9.sort_values(ascending=False)
print("Sorted Series in descending order:\n", sorted_series)

Sorted Series in descending order:
 2    8
0    5
4    4
1    2
3    1
dtype: int64


11. Sort Series by index.


In [ ]:
series10 = pd.Series([10, 20, 30], index=['c', 'a', 'b'])
sorted_by_index = series10.sort_index()
print("Series sorted by index:\n", sorted_by_index)

Series sorted by index:
 a    20
b    30
c    10
dtype: int64


12. Check for null values.



In [ ]:
series11 = pd.Series([1, 2, None, 4, 5])
null_check = series11.isnull()
print("Null values in series11:\n", null_check)

Null values in series11:
 0    False
1    False
2     True
3    False
4    False
dtype: bool


14. Concatenate two Series using concat().


In [ ]:
series12 = pd.Series([1, 2, 3])
series13 = pd.Series([4, 5, 6]) 
concatenated_series = pd.concat([series12, series13])
print("Concatenated Series:\n", concatenated_series)

Concatenated Series:
 0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64


15. Concatenate two Series using append().


In [7]:
# append() is not a part of pandas anymore, we use concat isnstead.

16. Retrieve first 5 elements using .head()



In [ ]:
series15 = pd.Series([10, 20, 30, 40, 50, 60])
first_five = series15.head(5)
print("First 5 elements of series15:\n", first_five)

First 5 elements of series15:
 0    10
1    20
2    30
3    40
4    50
dtype: int64


17. Retrieve last 5 elements using .tail()


In [ ]:
series16 = pd.Series([100, 200, 300, 400, 500, 600])
last_five = series16.tail(5)
print("Last 5 elements of series16:\n", last_five)

Last 5 elements of series16:
 1    200
2    300
3    400
4    500
5    600
dtype: int64


18. Convert Series to DataFrame.


In [ ]:
series17 = pd.Series([1, 2, 3, 4, 5])
df_from_series = series17.to_frame(name='Values')
print("DataFrame from Series:\n", df_from_series)

DataFrame from Series:
    Values
0       1
1       2
2       3
3       4
4       5


19. Replace NaN with 0.


In [ ]:
series18 = pd.Series([1, 2, None, 4, 5])
series18_filled = series18.fillna(0)
print("Series after replacing NaN with 0:\n", series18_filled)

Series after replacing NaN with 0:
 0    1.0
1    2.0
2    0.0
3    4.0
4    5.0
dtype: float64


20. Drop missing values.


In [ ]:
series19 = pd.Series([1, 2, None, 4, 5])
series19_dropped = series19.dropna()
print("Series after dropping missing values:\n", series19_dropped)

Series after dropping missing values:
 0    1.0
1    2.0
3    4.0
4    5.0
dtype: float64


In [18]:
series20 = pd.Series([1, 2, 3, 4, 5])
print("Data type of series20:", series20.dtype)

Data type of series20: int64
